# Ejercicios de NumPy - Módulo de Programación en Inteligencia Artificial

**Curso:** C.E. in IA y Big Data  
**Centro:** IES Ribera de Castilla  
**Profesor:** Jordi Pozo

## Nivel Básico: Creación y Atributos

**1. Importar NumPy**

Importa la librería NumPy con el alias `np`.

In [1]:
import numpy as np

**2. Crear un array 1D**

Crea un array de NumPy (1D) a partir de la siguiente lista de Python: `[1, 5, 9, 13]`

In [2]:
array_1=np.array([1,5,9,13])
print(array_1)

[ 1  5  9 13]


**3. Crear un array 2D (Matriz)**

Crea un array 2D (matriz) a partir de la siguiente lista anidada: `[[1, 2, 3], [4, 5, 6]]`

In [3]:
array_2=np.array([[1,2,3],[4,5,6]])
print(array_2)

[[1 2 3]
 [4 5 6]]


**4. Obtener la forma (shape)**

Crea la matriz del ejercicio 3 y muestra su `shape` (forma).

In [4]:
array_2.shape

(2, 3)

**5. Obtener el tipo de dato (dtype)**

Crea el array 1D del ejercicio 2 y muestra su `dtype` (tipo de dato).

In [5]:
array_1.dtype

dtype('int64')

**6. Crear un array de ceros**

Crea un array 1D de 6 elementos, donde todos sean ceros.

In [9]:
array_3=np.zeros(shape=(1,6))
print(array_3)

[[0. 0. 0. 0. 0. 0.]]


**7. Crear un array de unos (2D)**

Crea una matriz (array 2D) de 3x3 (3 filas, 3 columnas) donde todos los elementos sean unos.

In [11]:
array_4=np.ones(shape=(3,3))
print(array_4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**8. Crear un array con `arange`**

Crea un array que contenga todos los números enteros del 0 al 9.

In [12]:
array_5=np.arange(0,10)
print(array_5)

[0 1 2 3 4 5 6 7 8 9]


**9. Crear un array con `linspace`**

Crea un array de 5 elementos que estén espaciados uniformemente entre 0 y 1 (incluyendo ambos extremos).

In [13]:
array_6=np.linspace(0,1)
print(array_6)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


**10. Crear una matriz identidad**

Crea una matriz identidad de 4x4.

In [15]:
array_7=np.identity(n=4)
print(array_7)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Nivel Básico: Indexing y Slicing

**11. Acceder a un elemento (Indexing 1D)**

Dado el array `a = np.array([5, 10, 15, 20])`, accede al tercer elemento (valor `15`).

In [16]:
a=np.array([5,10,15,20])
print(a[2])

15


**12. Acceder a un elemento (Indexing 2D)**

Dada la matriz `m = np.array([[1, 2, 3], [4, 5, 6]])`, accede al elemento en la segunda fila, primera columna (valor `4`).

In [18]:
m = np.array([[1, 2, 3], [4, 5, 6]])
print(m[1,0])

4


**13. Slicing 1D (Sub-array)**

Dado el array `a = np.arange(10)`, crea un nuevo array que contenga los elementos del índice 2 al 5 (sin incluir el 5). El resultado debe ser `[2, 3, 4]`.

In [20]:
a=np.arange(10)
print(a)
a_2=a[2:5]
print(a_2)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


**14. Slicing 2D (Obtener una fila)**

Dada la matriz `m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`, obtén la segunda fila completa (`[4, 5, 6]`).

In [24]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m[1,:])

[4 5 6]


**15. Slicing 2D (Obtener una columna)**

Usando la misma matriz `m` del ejercicio anterior, obtén la tercera columna completa (`[3, 6, 9]`).

In [25]:
print(m[:,2])

[3 6 9]


## Nivel Medio: Operaciones y 'Ufuncs'

**16. Suma de arrays (elemento a elemento)**

Crea dos arrays, `a = np.array([1, 2, 3])` y `b = np.array([4, 5, 6])`. Súmalos.

In [26]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)

[5 7 9]


**17. Multiplicación por un escalar**

Dado el array `a = np.array([1, 2, 3])`, multiplícalo por 10.

In [27]:
a=np.array([1,2,3])
print(a*10)

[10 20 30]


**18. Aplicar una 'ufunc' (Función Universal)**

Dado el array `a = np.array([1, 4, 9, 16])`, calcula la raíz cuadrada (`sqrt`) de cada elemento.

In [28]:
a=np.array([1,4,9,16])
print(np.sqrt(a))

[1. 2. 3. 4.]


**19. Operación 'ufunc' (Exponencial)**

Calcula el exponencial (`np.exp`) del array `a = np.array([0, 1, 2])`.

In [29]:
a=np.array([0,1,2])
print(np.exp(a))

[1.         2.71828183 7.3890561 ]


**20. Crear un array aleatorio (distribución uniforme)**

Crea un array de 2x3 con números aleatorios distribuidos uniformemente entre 0 y 1.

In [33]:
a=np.linspace(0,1,6).reshape(2,3)
print(a)

[[0.  0.2 0.4]
 [0.6 0.8 1. ]]


**21. Crear un array aleatorio (distribución normal)**

Crea un array 1D de 100 elementos con números aleatorios siguiendo una distribución normal (media 0, desviación 1).

In [43]:
a=np.random.randint(0,100,100)
print(a.mean())

47.28


**22. Cambiar la forma (Reshape)**

Crea un array 1D con `np.arange(12)` (números del 0 al 11). Luego, cámbiale la forma (reshape) a una matriz de 3x4.

In [44]:
a=np.arange(12)
print(a.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Nivel Medio: Agregaciones y Estadísticas

**23. Suma de elementos (`np.sum`)**

Dado el array `a = np.array([1, 5, 10, 15, 20])`, calcula la suma total de sus elementos.

In [45]:
a=np.array([1,5,10,15,20])
print(a.sum())

51


**24. Media de elementos (`np.mean`)**

Usando el mismo array `a` del ejercicio anterior, calcula la media (promedio) de sus elementos.

In [46]:
print(a.mean())

10.2


**25. Desviación estándar y Varianza**

Calcula la desviación estándar (`np.std`) y la varianza (`np.var`) del array `a = np.array([1, 2, 3, 4, 5])`.

In [47]:
a=np.array([1,2,3,4,5])
print(np.std(a),np.var(a))

1.4142135623730951 2.0


**26. Mínimo y Máximo (`np.min`, `np.max`)**

Encuentra el valor mínimo y máximo del array `a = np.array([10, -5, 100, 3, 0])`.

In [49]:
a = np.array([10, -5, 100, 3, 0])
print(a.max(),a.min())

100 -5


**27. Agregación por eje (Suma de columnas)**

Dada la matriz `m = np.array([[1, 2, 3], [4, 5, 6]])`, calcula la suma de sus **columnas** (eje 0).

In [51]:
m = np.array([[1, 2, 3], 
              [4, 5, 6]])
print(m.sum(axis=0))

[5 7 9]


**28. Agregación por eje (Media de filas)**

Usando la misma matriz `m` del ejercicio anterior, calcula la media de sus **filas** (eje 1).

In [52]:
print(np.mean(m,axis=1))

[2. 5.]


## Nivel Medio: Indexación Avanzada y Lógica

**29. Filtrado con máscaras booleanas (Boolean Indexing)**

Dado el array `a = np.array([10, 20, 30, 40, 50])`, crea un nuevo array que contenga solo los elementos de `a` que sean **mayores que 25**.

In [53]:
a = np.array([10, 20, 30, 40, 50])
new_a=a[a>25]
print(new_a)

[30 40 50]


**30. Reemplazo condicional con `np.where`**

Dado el array `a = np.array([1, -5, 10, -3, 8, -2])`, crea un nuevo array donde todos los **números negativos** sean reemplazados por `0`.

In [58]:
a = np.array([1, -5, 10, -3, 8, -2])
new_a=np.where(a<0,0,a)
print(new_a)

[ 1  0 10  0  8  0]
